### ISSUE TITLE
Github workflow 중 `Deploy to Storybook to Chromatic`에서 에러 발생

### ISSUE THREAD

**Issue by algoORgoal** [uxplorerss/uxplorers-frontend#27]
## Summary

AS-IS
- Storybook을 chromatic의 public domain으로 배포하여 UI 변경 사항을 시각적으로 확인하고 싶다는 요청이 있었습니다.
- Github actions의 `Deploy Storybook to Chromatic`을 정의하여 main에 push될 때마다 ui 변경하도록 하였는데, deployment 과정에서 에러가 발생하였스빈다.

TO-BE
- main에 변경 사항이 들어올 때마다 Chromatic에 새로 배포합니다.

## Description

```
Error: ✖ Found only one commit
             This typically means you have ran into one of the following scenarios:
             - You've checked out a shallow copy of the Git repository, which actions/checkout@v2 does by default.
               In order for Chromatic to correctly determine baseline commits, we need access to the full Git history graph.
               With actions/checkout@v2, you can enable this by setting 'fetch-depth: 0'.
               ℹ Read more at https://www.chromatic.com/docs/github-actions
             - You've only made a single commit so far. 
               Please make at least one additional commit in order for Chromatic to be able to detect what's changed. 
                 at f8e (/home/runner/work/_actions/chromaui/action/latest/action/register.js:1001:625)
                 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                 at async fCs (/home/runner/work/_actions/chromaui/action/latest/action/register.js:1085:132)
                 at async Xve.task (/home/runner/work/_actions/chromaui/action/latest/action/register.js:[80](https://github.com/uxplorerss/uxplorers-frontend/actions/runs/11997437193/job/33443037642#step:5:81)3:24561)
```
## Root Cause
`storybook.yml`에 있는 actions/checkout@v4는 다음을 실행합니다.

1. `repository`를 클론한다.
2. 해당 branch로 checkout 한다.
3. commit history를 가져온다.

3의 과정에서 fetch-depth: 1(default)로 설정되어 있다면 lastest commit(가장 최근 커밋)만 가지고 오게 됩니다.
하지만 chromatic action에서는 프로젝트의 커밋 히스토리 전체를 확인해야 하기 때문에 에러를 발생시킵니다. 따라서 다음 에러가 발생하였습니다.

```
- You've checked out a shallow copy of the Git repository, which actions/checkout@v2 does by default.
               In order for Chromatic to correctly determine baseline commits, we need access to the full Git history graph.
               With actions/checkout@v2, you can enable this by setting 'fetch-depth: 0'.
```

- 여기서 shallow copy는 가장 최근 commit만 받아온 것이고, deep copy는 commit history를 전부 가져오는 것을 뜻합니다.

## Solution
actions/checkout@v4에 fetch-depth: 0 option을 추가합니다.

**Comment by algoORgoal** [comment]
처음 배포를 안 해서 그렇습니다. 이제부터 동작할 겁니다.
